set = set()
item = int(input("Enter the element(value) :"))
set.add(item)
item = int(input("Enter the element(value) :"))
set.add(item)
item = int(input("Enter the element(value) :"))
set.add(item)
item = int(input("Enter the element(value) :"))
set.add(item)
item = int(input("Enter the element(value) :"))
set.add(item)
item = int(input("Enter the element(value) :"))
set.add(item)
item = int(input("Enter the element(value) :"))
set.add(item)
item = int(input("Enter the element(value) :"))
set.add(item)

print(set)

